spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/jpa-board
    username: sa
    password:

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
