spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp:localhost/~/board-jpa
    username: sa
    password:

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
